import type { MarketSummary, NormalizedMarket, NormalizedPricePoint } from './domain.js';
import { mergeDataQualityFlags } from './validation.js';
const thresholds = [0.75, 0.8, 0.9, 0.95, 0.99] as const;
export function buildMarketSummary(market: NormalizedMarket, pricePoints: NormalizedPricePoint[]): MarketSummary {
  const ordered = [...pricePoints].sort((a,b)=>a.timestampMilliseconds-b.timestampMilliseconds);
  const up = priceStats(ordered.map((p)=>p.upPrice)); const down = priceStats(ordered.map((p)=>p.downPrice));
  const t = (field: 'upPrice'|'downPrice', threshold: number) => ordered.find((p)=>(p[field] ?? -Infinity) >= threshold) ?? null;
  return { marketSlug: market.marketSlug, conditionId: market.conditionId, marketDuration: market.marketDuration, marketStartTimestampMilliseconds: market.marketStartTimestampMilliseconds, marketEndTimestampMilliseconds: market.marketEndTimestampMilliseconds, targetPrice: market.targetPrice, winner: market.winner, isResolved: market.isResolved, pricePointsCount: ordered.length, firstTimestamp: ordered[0]?.timestampMilliseconds ?? null, lastTimestamp: ordered.at(-1)?.timestampMilliseconds ?? null, upPriceOpen: up.open, downPriceOpen: down.open, upPriceClose: up.close, downPriceClose: down.close, finalUpPrice: up.close, finalDownPrice: down.close, upPriceMinimum: up.minimum, upPriceMaximum: up.maximum, upPriceMean: up.mean, upPriceMedian: up.median, upPriceStandardDeviation: up.standardDeviation, downPriceMinimum: down.minimum, downPriceMaximum: down.maximum, downPriceMean: down.mean, downPriceMedian: down.median, downPriceStandardDeviation: down.standardDeviation,
    firstTimestampUpPriceGreaterThanOrEqual075: t('upPrice', thresholds[0])?.timestampMilliseconds ?? null, firstTimestampUpPriceGreaterThanOrEqual080: t('upPrice', thresholds[1])?.timestampMilliseconds ?? null, firstTimestampUpPriceGreaterThanOrEqual090: t('upPrice', thresholds[2])?.timestampMilliseconds ?? null, firstTimestampUpPriceGreaterThanOrEqual095: t('upPrice', thresholds[3])?.timestampMilliseconds ?? null, firstTimestampUpPriceGreaterThanOrEqual099: t('upPrice', thresholds[4])?.timestampMilliseconds ?? null,
    firstTimestampDownPriceGreaterThanOrEqual075: t('downPrice', thresholds[0])?.timestampMilliseconds ?? null, firstTimestampDownPriceGreaterThanOrEqual080: t('downPrice', thresholds[1])?.timestampMilliseconds ?? null, firstTimestampDownPriceGreaterThanOrEqual090: t('downPrice', thresholds[2])?.timestampMilliseconds ?? null, firstTimestampDownPriceGreaterThanOrEqual095: t('downPrice', thresholds[3])?.timestampMilliseconds ?? null, firstTimestampDownPriceGreaterThanOrEqual099: t('downPrice', thresholds[4])?.timestampMilliseconds ?? null,
    secondsLeftAtFirstUpPriceGreaterThanOrEqual075: t('upPrice', thresholds[0])?.secondsLeft ?? null, secondsLeftAtFirstUpPriceGreaterThanOrEqual080: t('upPrice', thresholds[1])?.secondsLeft ?? null, secondsLeftAtFirstUpPriceGreaterThanOrEqual090: t('upPrice', thresholds[2])?.secondsLeft ?? null, secondsLeftAtFirstUpPriceGreaterThanOrEqual095: t('upPrice', thresholds[3])?.secondsLeft ?? null, secondsLeftAtFirstUpPriceGreaterThanOrEqual099: t('upPrice', thresholds[4])?.secondsLeft ?? null,
    secondsLeftAtFirstDownPriceGreaterThanOrEqual075: t('downPrice', thresholds[0])?.secondsLeft ?? null, secondsLeftAtFirstDownPriceGreaterThanOrEqual080: t('downPrice', thresholds[1])?.secondsLeft ?? null, secondsLeftAtFirstDownPriceGreaterThanOrEqual090: t('downPrice', thresholds[2])?.secondsLeft ?? null, secondsLeftAtFirstDownPriceGreaterThanOrEqual095: t('downPrice', thresholds[3])?.secondsLeft ?? null, secondsLeftAtFirstDownPriceGreaterThanOrEqual099: t('downPrice', thresholds[4])?.secondsLeft ?? null, dataQualityFlags: mergeDataQualityFlags(market.dataQualityFlags, ...ordered.map((p)=>p.dataQualityFlags)) };
}
function priceStats(prices: Array<number | null>) { const present = prices.filter((p): p is number => p !== null); if (present.length === 0) return { open:null, close:null, minimum:null, maximum:null, mean:null, median:null, standardDeviation:null }; const mean = present.reduce((s,p)=>s+p,0)/present.length; return { open: present[0] ?? null, close: present.at(-1) ?? null, minimum: Math.min(...present), maximum: Math.max(...present), mean, median: median(present), standardDeviation: Math.sqrt(present.reduce((s,p)=>s+(p-mean)**2,0)/present.length) }; }
function median(values: number[]): number { const ordered = [...values].sort((a,b)=>a-b); const middle = Math.floor(ordered.length/2); return ordered.length % 2 === 0 ? ((ordered[middle-1] ?? 0)+(ordered[middle] ?? 0))/2 : ordered[middle] ?? 0; }
