import type { ParquetSchemaDefinition } from '../adapters/parquetWriter.js';
const optionalDouble = { type: 'DOUBLE', optional: true } as const;
const optionalInt64 = { type: 'INT64', optional: true } as const;
const optionalUtf8 = { type: 'UTF8', optional: true } as const;
export const marketsParquetSchema: ParquetSchemaDefinition = { market_slug: { type: 'UTF8' }, condition_id: optionalUtf8, question: { type: 'UTF8' }, market_duration: { type: 'UTF8' }, market_start_timestamp_milliseconds: { type: 'INT64' }, market_end_timestamp_milliseconds: { type: 'INT64' }, up_token_id: optionalUtf8, down_token_id: optionalUtf8, target_price: optionalDouble, winner: optionalUtf8, is_resolved: { type: 'BOOLEAN' }, is_closed: { type: 'BOOLEAN' }, raw_outcomes: { type: 'UTF8' }, raw_outcome_prices: { type: 'UTF8' }, data_quality_flags: { type: 'UTF8' } };
export const pricePointsParquetSchema: ParquetSchemaDefinition = { market_slug: { type: 'UTF8' }, condition_id: optionalUtf8, market_duration: { type: 'UTF8' }, timestamp_milliseconds: { type: 'INT64' }, timestamp_iso: { type: 'UTF8' }, seconds_left: { type: 'INT64' }, up_price: optionalDouble, down_price: optionalDouble, target_price: optionalDouble, winner: optionalUtf8, is_resolved: { type: 'BOOLEAN' }, data_quality_flags: { type: 'UTF8' }, future_maximum_up_price: optionalDouble, future_maximum_down_price: optionalDouble, future_minimum_up_price: optionalDouble, future_minimum_down_price: optionalDouble, future_final_up_price: optionalDouble, future_final_down_price: optionalDouble, future_reaches_up_075: { type: 'BOOLEAN' }, future_reaches_up_080: { type: 'BOOLEAN' }, future_reaches_up_090: { type: 'BOOLEAN' }, future_reaches_up_095: { type: 'BOOLEAN' }, future_reaches_up_099: { type: 'BOOLEAN' }, future_reaches_down_075: { type: 'BOOLEAN' }, future_reaches_down_080: { type: 'BOOLEAN' }, future_reaches_down_090: { type: 'BOOLEAN' }, future_reaches_down_095: { type: 'BOOLEAN' }, future_reaches_down_099: { type: 'BOOLEAN' } };
export const marketSummaryParquetSchema: ParquetSchemaDefinition = { market_slug: { type: 'UTF8' }, condition_id: optionalUtf8, market_duration: { type: 'UTF8' }, market_start_timestamp_milliseconds: { type: 'INT64' }, market_end_timestamp_milliseconds: { type: 'INT64' }, target_price: optionalDouble, winner: optionalUtf8, is_resolved: { type: 'BOOLEAN' }, price_points_count: { type: 'INT64' }, first_timestamp: optionalInt64, last_timestamp: optionalInt64, up_price_open: optionalDouble, down_price_open: optionalDouble, up_price_close: optionalDouble, down_price_close: optionalDouble, final_up_price: optionalDouble, final_down_price: optionalDouble, up_price_min: optionalDouble, up_price_max: optionalDouble, up_price_mean: optionalDouble, up_price_median: optionalDouble, up_price_stdev: optionalDouble, down_price_min: optionalDouble, down_price_max: optionalDouble, down_price_mean: optionalDouble, down_price_median: optionalDouble, down_price_stdev: optionalDouble, first_up_reaches_075_timestamp: optionalInt64, first_up_reaches_080_timestamp: optionalInt64, first_up_reaches_090_timestamp: optionalInt64, first_up_reaches_095_timestamp: optionalInt64, first_up_reaches_099_timestamp: optionalInt64, first_down_reaches_075_timestamp: optionalInt64, first_down_reaches_080_timestamp: optionalInt64, first_down_reaches_090_timestamp: optionalInt64, first_down_reaches_095_timestamp: optionalInt64, first_down_reaches_099_timestamp: optionalInt64, first_up_reaches_075_seconds_left: optionalInt64, first_up_reaches_080_seconds_left: optionalInt64, first_up_reaches_090_seconds_left: optionalInt64, first_up_reaches_095_seconds_left: optionalInt64, first_up_reaches_099_seconds_left: optionalInt64, first_down_reaches_075_seconds_left: optionalInt64, first_down_reaches_080_seconds_left: optionalInt64, first_down_reaches_090_seconds_left: optionalInt64, first_down_reaches_095_seconds_left: optionalInt64, first_down_reaches_099_seconds_left: optionalInt64, data_quality_flags: { type: 'UTF8' } };
export const strategyTrainingRowsParquetSchema: ParquetSchemaDefinition = { ...pricePointsParquetSchema, up_wins_binary: optionalInt64, up_price_change_previous_1_point: optionalDouble, down_price_change_previous_1_point: optionalDouble, up_price_change_previous_2_points: optionalDouble, down_price_change_previous_2_points: optionalDouble, up_price_change_previous_3_points: optionalDouble, down_price_change_previous_3_points: optionalDouble };
export const rejectedMarketsParquetSchema: ParquetSchemaDefinition = { market_slug: optionalUtf8, condition_id: optionalUtf8, question: optionalUtf8, detected_market_duration: optionalUtf8, rejection_reason: { type: 'UTF8' }, raw_market_file_path: { type: 'UTF8' }, data_quality_flags: { type: 'UTF8' } };
